shared: &shared
  adapter: postgresql
  encoding: unicode
  pool: 15
  username: postgres
  password: 
  host: localhost

development:
  <<: *shared
  database: ttt_development

test:
  <<: *shared
  database: ttt_test
